# Generated by Django 3.0.5 on 2020-04-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2500)),
                ('source', models.CharField(max_length=100)),
                ('auction_title', models.CharField(max_length=500)),
                ('lot_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('image_url', models.CharField(max_length=5000, null=True)),
                ('details_url', models.CharField(max_length=5000, null=True)),
                ('is_sold', models.BooleanField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('sold_currency', models.CharField(max_length=50, null=True)),
                ('grading', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=500, null=True)),
                ('model', models.CharField(max_length=500, null=True)),
                ('year', models.CharField(max_length=500, null=True)),
                ('reference', models.CharField(max_length=500, null=True)),
                ('case_no', models.CharField(max_length=500, null=True)),
                ('numbers', models.CharField(max_length=500, null=True)),
                ('caliber', models.CharField(max_length=500, null=True)),
                ('bracelet', models.CharField(max_length=500, null=True)),
                ('signature', models.CharField(max_length=500, null=True)),
                ('accessories', models.CharField(max_length=500, null=True)),
                ('dimensions', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionSCP.Lot')),
            ],
        ),
    ]
